version: '3.8'
services:
  rabbitmq3:
    build:
      dockerfile: docker/Dockerfile
      context: .
    container_name: "rabbitmq_test"
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - rabbitmq_net


networks:
  rabbitmq_net:
    driver: bridge

